baseURL = "http://juan-fernandez.netlify.app"
languageCode = "en-us"
title = "Juan Fernandez Arias"
theme = "personal-web"
copyright="Â© Juan Fernandez"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true


[params.intro]
  main = "Hi, I'm Juan :wave:"
  sub = "I'm a Hardware Engineer and Maker"

[params.main]
  latestPublishHeader = "My Latest Project"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = 'rgba(0,0,0,0.0)' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = 'rgba(0,0,0,0.255),rgba(0,0,0,0.255)' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "images/juan-square.jpg" # - default "/images/edna-west.jpg"
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/"
  twitter = "https://twitter.com/"
  linkedin = "https://www.linkedin.com/in/"
  medium = "https://medium.com/"
  codepen = "https://codepen.io/"
  facebook = "https://www.facebook.com/"
  youtube = "https://www.youtube.com/"
  instagram = "https://www.instagram.com/"
  gitlab = "https://gitlab.com/"
  keybase = "https://keybase.io/"

[params.contact]
  email = ""
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "blog"
  name = "Post"
  title = "Blog section"
  url = "/post/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false